steps:

  - name: gcr.io/k8s-skaffold/pack
    entrypoint: pack
    args:
      - build
      - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - --builder=gcr.io/buildpacks/builder:v1
      - --network=cloudbuild
      - --path=.

 
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA


  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --platform=$_PLATFORM
      - --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - --region=$_DEPLOY_REGION
      - --allow-unauthenticated
      - --quiet

images:
  - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_HOSTNAME: europe-west1-docker.pkg.dev
  _DEPLOY_REGION: europe-west1
  _PLATFORM: managed
  _SERVICE_NAME: eosmapper
  _TRIGGER_ID: auto
